import "./globals.css";
import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { ErrorBoundary } from "@/providers/ErrorBoundary";
import { NextUIProvider } from "@/providers/NextUI";
import { QueryClientProvider } from "@/providers/QueryClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full" dir="rtl">
      <body className={(inter.className, "h-full min-h-full")}>
        <ErrorBoundary>
          <QueryClientProvider>
            <NextUIProvider className="mx-auto flex h-full flex-col">
              {children}
            </NextUIProvider>
          </QueryClientProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
